export const templates = [
  "Software Engineer",
  "Product Manager",
  "Data Analyst",
  "UI Designer",
  "UX Designer",
  "Data Scientist",
  "DevOps Engineer",
  "Marketing Manager",
  "Graphic Designer",
  "Business Analyst",
  "Financial Analyst",
  "Auditor",
  "Consultant",
  "Architect",
  "Civil Engineer",
  "Electrical Engineer",
  "Chemical Engineer",
  "Admin",
  "Finance Manager",
  "Mechanical Engineer",
  "HR Manager",
  "Recruiter",
  "Accountant",
  "Sales Manager",
  "Sales Executive",
  "Operations Manager",
  "Project Manager",
  "Consultant",
  "Lawyer",
  "Doctor",
  "Surgeon",
  "Physician",
  "Therapist",
  "Psychiatrist",
  "Dentist",
  "Pharmacist",
  "Psychologist",
  "Helper",
  "Designer",
  "Teacher",
  "Nurse",
  "Customer Service Representative",
  "Content Creator",
  "Social Media Manager",
  "Digital Marketer",
  "Web Developer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "iOS Developer",
  "Android Developer",
  "React Developer",
];
